### PR TITLE
Fix queue success logic

### LINKED ISSUE #13: Queueing work always fails unless the batch queue is empty
eg:

```ruby
batch1 = Resque::Plugins::Batch.new
batch2 = Resque::Plugins::Batch.new

10.times { batch1.enqueue(Batch2QueueJob) }
10.times { batch2.enqueue(Batch2QueueJob) }
t1 = Thread.new { batch1.perform }
t2 = Thread.new { batch2.perform } # => RuntimeError: not all jobs were queued
t1.join
t2.join
```

### LINKED ISSUE #14: Queueing work to different queues in the same batch fails
eg:
```ruby
batch1 = Resque::Plugins::Batch.new

10.times { batch1.enqueue(Job) }
10.times { batch1.enqueue(Batch2QueueJob) }
batch1.perform # => RuntimeError: not all jobs were queued
```

### PR DESCRIPTION
**Pull request by sam-carlberg**
Now explicitly looks for the queued jobs for confirmation, rather than assuming the size of the queue the last job was queued to will be the number of queued jobs

Fixes #13 and fixes #14

### CODE REVIEW

File: lib/resque/plugins/batch.rb [hunk 1]
```diff
@@ -88,8 +96,19 @@ def perform
...
 
         unless Resque.inline
-          unless result.last == job_count
-            raise "not all jobs were queued"
+          # Get all the jobs in each queue, then confirm that the jobs we
+          # just queued up are all present
+          expected_queue_jobs.each do |queue_name, expected_jobs|
+            currently_queued_jobs =
+              redis.lrange("queue:#{queue_name}", 0, -1)
+                   .map(&JSON.method(:load))
```
Comment (sam-carlberg) [inline lib/resque/plugins/batch.rb:104]: Should probably be `map(&Resque.method(:decode))` instead

File: lib/resque/plugins/batch.rb [hunk 2]
```diff
@@ -88,8 +96,19 @@ def perform
...
+          expected_queue_jobs.each do |queue_name, expected_jobs|
+            currently_queued_jobs =
+              redis.lrange("queue:#{queue_name}", 0, -1)
+                   .map(&Resque.method(:decode))
+
+            unqueued_jobs =
+              expected_jobs.reject { |job_hash| currently_queued_jobs.include?(job_hash) }
+
+            if unqueued_jobs.any?
+              raise "#{unqueued_jobs.size} job(s) were unable to be queued to the #{queue_name.inspect} queue"
```
Comment (sam-carlberg) [inline lib/resque/plugins/batch.rb:110]: If an error is raised here, `Batch#perform` will exit immediately and yield to the caller. This could be a problem since any successfully queued batch job will stay queued and run as normal, but the caller would have no indication of it.
